### ISSUE TITLE
Compiling on Mac OS X 10.10 Yosemite

### ISSUE THREAD

**Issue by fhorlaville** [nextreports/nextreports-designer#1]
Hi,

I've pulled 7.4 from git but I can't get it to compile on Mac OS X 10.10 (Yosemite). Apparently there are some files missing (Excel exporter)

I tried with both latest JDK 1.7 and 1.8. Please see the errors I have with 1.8 (similar to those in 1.7) in the next message (apparently this one is too big to post)

Thanks a lot,

Franck Horlaville
Senior Systems Engineer
Prism-DM

```
compile:
    [mkdir] Created dir: /Users/franck/Documents/Projects/nextreports-designer/target/classes
    [javac] /Users/franck/Documents/Projects/nextreports-designer/build.xml:119: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 605 source files to /Users/franck/Documents/Projects/nextreports-designer/target/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] /Users/franck/Documents/Projects/nextreports-designer/src/ro/nextreports/designer/action/report/layout/export/ExportToExcelXAction.java:12: error: cannot find symbol
    [javac] import ro.nextreports.engine.exporter.XlsxExporter;
    [javac]                                      ^
    [javac]   symbol:   class XlsxExporter
    [javac]   location: package ro.nextreports.engine.exporter
    [javac] /Users/franck/Documents/Projects/nextreports-designer/src/ro/nextreports/designer/datasource/DefaultDataSourceManager.java:33: warning: BASE64Encoder is internal proprietary API and may be removed in a future release
    [javac] import sun.misc.BASE64Encoder;
    [javac]                ^
    [javac] /Users/franck/Documents/Projects/nextreports-designer/src/ro/nextreports/designer/datasource/DefaultDataSourceManager.java:34: warning: BASE64Decoder is internal proprietary API and may be removed in a future release
    [javac] import sun.misc.BASE64Decoder;
    [javac]                ^
    [javac] /Users/franck/Documents/Projects/nextreports-designer/src/ro/nextreports/designer/action/report/layout/export/ExportToExcelXAction.java:18: error: cannot find symbol
    [javac]         exportType = ReportRunner.EXCEL_XLSX_FORMAT;
    [javac]                                  ^
    [javac]   symbol:   variable EXCEL_XLSX_FORMAT
    [javac]   location: class ReportRunner
    [javac] /Users/franck/Documents/Projects/nextreports-designer/src/ro/nextreports/designer/action/report/layout/export/ExportToExcelXAction.java:37: error: cannot find symbol
    [javac]         ResultExporter exporter = new XlsxExporter(bean);
    [javac]                                       ^
    [javac]   symbol:   class XlsxExporter
    [javac]   location: class ExportToExcelXAction
    [javac] /Users/franck/Documents/Projects/nextreports-designer/src/ro/nextreports/designer/datasource/DefaultDataSourceManager.java:220: warning: BASE64Encoder is internal proprietary API and may be removed in a future release
    [javac]             return new BASE64Encoder().encode(enc.getBytes(CHARSET_NAME));
    [javac]                        ^
    [javac] /Users/franck/Documents/Projects/nextreports-designer/src/ro/nextreports/designer/datasource/DefaultDataSourceManager.java:228: warning: BASE64Decoder is internal proprietary API and may be removed in a future release
    [javac]             byte[] bytes = new BASE64Decoder().decodeBuffer(cipherText);
    [javac]                                ^
    [javac] /Users/franck/Documents/Projects/nextreports-designer/src/ro/nextreports/designer/ui/sqleditor/syntax/SyntaxView.java:63: warning: [deprecation] setGraphicsStyle(Graphics,TokenType) in SyntaxStyles has been deprecated
    [javac]                     SyntaxStyles.getInstance().setGraphicsStyle(graphics,
    [javac]                                               ^
    [javac] /Users/franck/Documents/Projects/nextreports-designer/src/ro/nextreports/designer/ui/sqleditor/syntax/SyntaxView.java:89: warning: [deprecation] setGraphicsStyle(Graphics,TokenType) in SyntaxStyles has been deprecated
    [javac]                 SyntaxStyles.getInstance().setGraphicsStyle(graphics, TokenType.DEFAULT);
    [javac]                                           ^
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 3 errors
    [javac] 7 warnings

BUILD FAILED
/Users/franck/Documents/Projects/nextreports-designer/build.xml:119: Compile failed; see the compiler error output for details.
```

**Comment by decebals** [comment]
I updated the SNAPSHOT versions for engine and server(client-api) on maven central repository. Please try again to build the designer.
The idea is that the designer depends by engine and the client api part of the server. So the flow is to download and build on your machine that dependencies before try to build the designer.

**Comment by decebals** [comment]
`XlsxExporter` class is in engine and not in designer so there's no missing code.

**Comment by fhorlaville** [comment]
I'm using the 7.3 server from the downloads on a linux server and the designer on my local machine - I'm going to the git version on the client side because of the other issue I raised which you fixed (with UNSIGNED DECIMAL). I had not thought of compiling the server to get the designer to work.

I am however very pleased to report that designer commit a65a6f5 now compiles fine ! Thanks a lot ! And the other issue has been solved as well. You're a star!
